enum Eroutes {
    ROOT = 'Root',
    HOME_SCREEN = 'HOME_SCREEN',
    AGENDA_SCREEN = 'AGENDA_SCREEN',
    MAP_SCREEN = 'MAP_SCREEN',
    ALERTS_SCREEN = 'ALERTS_SCREEN',
    READER_SCREEN = 'READER_SCREEN',
    RESEARCH_SCREEN = 'RESEARCH_SCREEN',
    EVENT_DETAILS_SCREEN = 'EVENT_DETAILS_SCREEN',
    LOCATION_DETAILS_SCREEN = 'LOCATION_DETAILS_SCREEN'
}

export default Eroutes
